Script started on 2017年03月11日 (週六) 11時50分24秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Git $[00m whoami; pwd
pd2vm
/home/pd2vm/Git
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Git $[00m git config -l
user.name=CaesarTseng
user.email=dpowerman37@gmail.com
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Git $[00m git clone https://githun.[K[Kb.com/CaesarTseng/lab1.git [A
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Git $[00m exit

Script done on 2017年03月11日 (週六) 11時51分55秒
